#!/usr/bin/env python3
"""
extract_icc.py — pull every embedded ICC profile out of a tree of PDF files.

WHY THIS EXISTS
===============
`iccce` claims to parse ICC profiles. Every profile it has been tested
against so far is either synthetic (generated by `tools/gen-profiles`),
shipped by the operating system (the Windows `.icm` set), or supplied by
a standards body (FOGRA51 via ECI). None of those is *what a real
document producer actually embeds*, and the difference matters: rule 6
of this project says the parser reports rather than repairs, which is
only a virtue if the parser has been pointed at files that were written
by somebody else's exporter.

The Ghent PDF Output Suite 5.0 is a corpus of PDF/X test patches written
by Adobe InDesign CS6 and imposed by Callas pdfToolbox — i.e. by the
mainstream graphic-arts toolchain. Its ICC-CMS category deliberately
embeds ICC v2 *and* ICC v4 profiles as image source spaces, plus a PDF/X
`/OutputIntents` destination profile per file. That makes it the closest
thing this project has to a population sample of real-world profiles,
and running the parser across it is a *compatibility* measurement that
needs no press, no spectrophotometer and no proofing device.

WHAT IT DOES
============
Walks a directory tree of PDFs. For every indirect object in every file
that is a stream, it decodes the stream and applies the one unambiguous
test for an ICC profile: **bytes 36..40 of an ICC profile are the ASCII
signature `acsp`** (ICC.1:2022 §7.2.5, the profile file signature field
of the profile header). Anything that matches is written out.

Deliberately NOT done here:

* No attempt to understand PDF colour-space syntax. An ICCBased colour
  space is `[/ICCBased <stream>]` and an output intent's profile is
  `/DestOutputProfile <stream>`, but a profile can also hang off an
  image's `/ColorSpace`, an alternate space, a soft-mask group, or a
  page group. Deciding which is which is `pdfce`'s half of the boundary
  (see the request channel's README), not this project's. The `acsp`
  test finds all of them regardless of how they are referenced, which is
  exactly what a *parser* compatibility sweep wants.
* No repair, no normalisation, no re-serialisation. Bytes come out as
  they went in, so that whatever the parser then says about them is a
  statement about the producer's file and not about this script.

DEDUPLICATION
=============
The same profile (sRGB IEC61966-2.1, Coated FOGRA39, …) is embedded once
per PDF that uses it, so a naive dump produces dozens of byte-identical
copies. Files are named by the SHA-256 of their contents, so identical
profiles collapse to one file, and the manifest records every
(pdf, object number) that produced each one. The count of *distinct*
profiles is the number that means anything.

OUTPUT
======
    <outdir>/<sha256[:16]>.icc      the profile bytes, verbatim
    <outdir>/manifest.json          one record per distinct profile:
                                      sha256, size, and every source
                                      (pdf path, object id) it came from

LICENSING — READ THIS BEFORE MOVING THE OUTPUT
==============================================
The Ghent PDF Output Suite's own licence permits use only for "testing
workflow setup" and forbids commercial use or redistribution without
written permission. The ICC profiles inside the patches carry their own
separate licences (Adobe's, ECI's, the ICC's). **Neither the patches nor
the extracted profiles may be committed to this MIT repository.** The
default output directory is therefore inside
`D:\Dev\iccce-private-fixtures\`, alongside the other three
differently-licensed corpora, exactly as `docs/NEXT_SESSION.md` §4
requires.

USAGE
=====
    python tools/ghent/extract_icc.py <pdf-root> <outdir>

Exit codes: 0 profiles found; 1 none found (which is a finding, not a
success); 2 usage error.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

try:
    from pypdf import PdfReader
    from pypdf.generic import IndirectObject
except ImportError:  # pragma: no cover - environment guard
    sys.stderr.write("extract_icc.py: requires pypdf (`pip install pypdf`)\n")
    raise SystemExit(2)

# ICC.1:2022 §7.2.5 — the profile file signature. Bytes 36..40 of the
# 128-byte profile header are always the ASCII string 'acsp'. This is the
# field a reader is told to use to recognise an ICC profile, and it is the
# only field with a fixed value, which is why it is the whole test here.
ICC_SIGNATURE_OFFSET = 36
ICC_SIGNATURE = b"acsp"

# The ICC header is 128 bytes and is followed by a 4-byte tag count, so no
# real profile is shorter than 132 bytes. Anything smaller that happens to
# contain 'acsp' is a coincidence, not a profile.
ICC_MIN_LENGTH = 132


def looks_like_icc(data: bytes) -> bool:
    """True if `data` carries the ICC profile file signature.

    Deliberately weak: it does not check that the declared profile size
    matches the buffer, nor that the version is one iccce supports. A
    truncated or malformed profile is precisely the interesting case —
    letting it through to the parser is the point of the exercise, and
    silently filtering it here would hide exactly the malformation the
    parser exists to report.
    """
    if len(data) < ICC_MIN_LENGTH:
        return False
    end = ICC_SIGNATURE_OFFSET + len(ICC_SIGNATURE)
    return data[ICC_SIGNATURE_OFFSET:end] == ICC_SIGNATURE


def scan_pdf(path: Path) -> list[tuple[int, bytes]]:
    """Return every (object number, decoded stream) in `path` that is ICC.

    Walks object numbers 1..len(xref) rather than following the document
    structure, because following the structure would require modelling
    PDF colour spaces — the consumer's job, not ours. Every failure to
    resolve or decode an object is swallowed: a PDF/X test suite contains
    files with deliberately awkward constructs, and one unreadable object
    must not abort the sweep of the other several thousand.
    """
    found: list[tuple[int, bytes]] = []
    reader = PdfReader(str(path))
    # `len(reader.xref)` is unreliable across pypdf versions; the highest
    # object number is derived from the trailer's /Size where present.
    try:
        size = int(reader.trailer["/Size"])
    except Exception:
        size = 20000

    for objnum in range(1, size):
        try:
            obj = IndirectObject(objnum, 0, reader).get_object()
        except Exception:
            continue
        if obj is None or not hasattr(obj, "get_data"):
            continue
        try:
            data = obj.get_data()
        except Exception:
            # A stream whose filter we cannot run (JPXDecode, a broken
            # Flate stream) cannot be an ICC profile we could parse
            # anyway. Record nothing; the absence is not interesting.
            continue
        if looks_like_icc(data):
            found.append((objnum, data))
    return found


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        sys.stderr.write(__doc__ or "")
        sys.stderr.write("\nusage: extract_icc.py <pdf-root> <outdir>\n")
        return 2

    root = Path(argv[1])
    outdir = Path(argv[2])
    outdir.mkdir(parents=True, exist_ok=True)

    pdfs = sorted(p for p in root.rglob("*.pdf"))
    if not pdfs:
        sys.stderr.write(f"extract_icc.py: no PDFs under {root}\n")
        return 1

    # sha256 -> {"size": int, "sources": [{"pdf": str, "object": int}]}
    by_hash: dict[str, dict] = {}

    for pdf in pdfs:
        rel = str(pdf.relative_to(root))
        try:
            hits = scan_pdf(pdf)
        except Exception as exc:
            sys.stderr.write(f"  ! {rel}: unreadable ({exc})\n")
            continue
        for objnum, data in hits:
            digest = hashlib.sha256(data).hexdigest()
            rec = by_hash.setdefault(
                digest, {"size": len(data), "sources": []}
            )
            rec["sources"].append({"pdf": rel, "object": objnum})
        print(f"  {rel}: {len(hits)} ICC stream(s)")

    # Second pass to write bytes: re-read rather than hold every profile in
    # memory across the whole corpus. Profiles are up to ~2 MB each and the
    # corpus is ~70 files; holding them all is fine in practice, but the
    # re-read keeps peak memory proportional to one PDF.
    written: set[str] = set()
    for pdf in pdfs:
        rel = str(pdf.relative_to(root))
        try:
            hits = scan_pdf(pdf)
        except Exception:
            continue
        for _objnum, data in hits:
            digest = hashlib.sha256(data).hexdigest()
            if digest in written:
                continue
            (outdir / f"{digest[:16]}.icc").write_bytes(data)
            written.add(digest)

    manifest = {
        "source_root": str(root),
        "distinct_profiles": len(by_hash),
        "total_embeddings": sum(len(r["sources"]) for r in by_hash.values()),
        "pdfs_scanned": len(pdfs),
        "profiles": [
            {"sha256": d, "file": f"{d[:16]}.icc", **rec}
            for d, rec in sorted(by_hash.items())
        ],
    }
    (outdir / "manifest.json").write_text(json.dumps(manifest, indent=2))

    print(
        f"\n{len(by_hash)} distinct profile(s) from "
        f"{manifest['total_embeddings']} embedding(s) across {len(pdfs)} PDF(s)"
    )
    return 0 if by_hash else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
